// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5wR90oxl2p31wTFhB-sY8rkR2CPc3YUg',
    appId: '1:407286126076:web:c31619165b36af1e740e79',
    messagingSenderId: '407286126076',
    projectId: 'pingolearndemo-8a94a',
    authDomain: 'pingolearndemo-8a94a.firebaseapp.com',
    storageBucket: 'pingolearndemo-8a94a.appspot.com',
    measurementId: 'G-TLNW7Y0J1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGKsiMP88iSZA9ZNosTfeXEMLTjQqDW18',
    appId: '1:407286126076:android:0012dad1d54df75e740e79',
    messagingSenderId: '407286126076',
    projectId: 'pingolearndemo-8a94a',
    storageBucket: 'pingolearndemo-8a94a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUZ6ItrKrF4jJE2vUmVMKRf8udP11jOpQ',
    appId: '1:407286126076:ios:74f43b6547eb2436740e79',
    messagingSenderId: '407286126076',
    projectId: 'pingolearndemo-8a94a',
    storageBucket: 'pingolearndemo-8a94a.appspot.com',
    iosBundleId: 'com.example.pingoLearnDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUZ6ItrKrF4jJE2vUmVMKRf8udP11jOpQ',
    appId: '1:407286126076:ios:74f43b6547eb2436740e79',
    messagingSenderId: '407286126076',
    projectId: 'pingolearndemo-8a94a',
    storageBucket: 'pingolearndemo-8a94a.appspot.com',
    iosBundleId: 'com.example.pingoLearnDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5wR90oxl2p31wTFhB-sY8rkR2CPc3YUg',
    appId: '1:407286126076:web:c74b59e15bd64809740e79',
    messagingSenderId: '407286126076',
    projectId: 'pingolearndemo-8a94a',
    authDomain: 'pingolearndemo-8a94a.firebaseapp.com',
    storageBucket: 'pingolearndemo-8a94a.appspot.com',
    measurementId: 'G-L9B6B4SP4G',
  );

}